const { contextBridge, ipcRenderer } = require("electron");

function subscription(channel, listener) {
  const wrapped = (_event, value) => listener(value);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld("codexWebLauncher", {
  snapshot: () => ipcRenderer.invoke("launcher:snapshot"),
  councilRuntime: () => ipcRenderer.invoke("launcher:council-runtime-snapshot"),
  setLanguage: (language) => ipcRenderer.invoke("launcher:set-language", language),
  openSocial: (target) => ipcRenderer.invoke("launcher:open-social", target),
  completeOnboarding: (language) => ipcRenderer.invoke("launcher:complete-onboarding", language),
  openExternal: (url) => ipcRenderer.invoke("launcher:open-external", url),
  setBrowserBounds: (bounds) => ipcRenderer.invoke("launcher:browser-bounds", bounds),
  setBrowserSurfaceActive: (active) => ipcRenderer.invoke("launcher:browser-surface-active", active),
  showBrowser: () => ipcRenderer.invoke("launcher:browser-show"),
  hideBrowser: () => ipcRenderer.invoke("launcher:browser-hide"),
  navigateBrowser: (action) => ipcRenderer.invoke("launcher:browser-navigate", action),
  zoomBrowser: (action) => ipcRenderer.invoke("launcher:browser-zoom", action),
  selectBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-select", tabId),
  closeBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-close", tabId),
  openLogin: () => ipcRenderer.invoke("launcher:browser-login"),
  logoutChatGpt: () => ipcRenderer.invoke("launcher:browser-logout"),
  dismissSessionReminder: () => ipcRenderer.invoke("launcher:session-reminder-dismiss"),
  smokeTest: () => ipcRenderer.invoke("launcher:browser-smoke"),
  verifyMcp: () => ipcRenderer.invoke("launcher:mcp-verify"),
  doctor: () => ipcRenderer.invoke("launcher:doctor"),
  cancelTurns: () => ipcRenderer.invoke("launcher:cancel-turns"),
  setupMcp: (input) => ipcRenderer.invoke("launcher:setup-mcp", input),
  bindCurrentChatGptAsLead: (input = {}) => ipcRenderer.invoke("launcher:council-bind-current-lead", input),
  focusCouncilAgent: (agentId) => ipcRenderer.invoke("launcher:council-agent-focus", agentId),
  councilExecutionRuns: () => ipcRenderer.invoke("launcher:council-execution-runs"),
  projectRelayList: () => ipcRenderer.invoke("launcher:project-relay-list"),
  projectRelayStart: (input) => ipcRenderer.invoke("launcher:project-relay-start", input),
  projectRelayCancel: (id) => ipcRenderer.invoke("launcher:project-relay-cancel", id),
  councilExecutionRun: (runId) => ipcRenderer.invoke("launcher:council-execution-read", runId),
  councilExecutionEvents: (runId) => ipcRenderer.invoke("launcher:council-execution-events", runId),
  councilExecutionReceipts: () => ipcRenderer.invoke("launcher:council-execution-receipts"),
  cancelCouncilExecution: (runId) => ipcRenderer.invoke("launcher:council-execution-cancel", runId),
  focusCouncilExecutionAgent: (agentId) => ipcRenderer.invoke("launcher:council-execution-focus", agentId),
  captureCouncilExecutionAgent: (agentId) => ipcRenderer.invoke("launcher:council-execution-capture", agentId),
  retryCouncilExecution: (runId) => ipcRenderer.invoke("launcher:council-execution-retry", runId),
  councilSupervisorStatus: () => ipcRenderer.invoke("launcher:council-supervisor-status"),
  setCouncilSupervisorManager: (agentId) => ipcRenderer.invoke("launcher:council-supervisor-manager", agentId),
  runCouncilSupervisorNow: () => ipcRenderer.invoke("launcher:council-supervisor-run"),
  councilObservations: () => ipcRenderer.invoke("launcher:council-observations-list"),
  councilObservationStorage: () => ipcRenderer.invoke("launcher:council-observation-storage"),
  councilObservation: (runId) => ipcRenderer.invoke("launcher:council-observation-read", runId),
  councilObservationScreenshot: (runId, screenshotId) => ipcRenderer.invoke("launcher:council-observation-screenshot", runId, screenshotId),
  deleteCouncilObservation: (runId) => ipcRenderer.invoke("launcher:council-observation-delete", runId),
  clearCouncilObservations: () => ipcRenderer.invoke("launcher:council-observations-clear"),
  councilAutonomyStatus: () => ipcRenderer.invoke("launcher:council-autonomy-status"),
  councilExceptionalWork: () => ipcRenderer.invoke("launcher:council-autonomy-exceptional"),
  cancelCouncilExceptionalWork: (workItemId) => ipcRenderer.invoke("launcher:council-autonomy-cancel", workItemId),
  retryCouncilUncertainWork: (workItemId) => ipcRenderer.invoke("launcher:council-autonomy-retry-uncertain", workItemId),
  councilMemoryStats: (roomId = null) => ipcRenderer.invoke("launcher:council-memory-stats", roomId),
  councilMemorySearch: (roomId, query, limit = 20) => ipcRenderer.invoke("launcher:council-memory-search", roomId, query, limit),
  councilMemoryRecent: (roomId, limit = 30) => ipcRenderer.invoke("launcher:council-memory-recent", roomId, limit),
  clearCouncilProjectMemory: (roomId) => ipcRenderer.invoke("launcher:council-memory-clear-project", roomId),
  setMcpStep: (step) => ipcRenderer.invoke("launcher:set-mcp-step", step),
  setAutostart: (enabled) => ipcRenderer.invoke("launcher:autostart", enabled),
  setPreference: (key, value) => ipcRenderer.invoke("launcher:set-preference", key, value),
  setSidebarState: (state) => ipcRenderer.invoke("launcher:sidebar-state", state),
  logs: (limit) => ipcRenderer.invoke("launcher:logs", limit),
  openLogs: () => ipcRenderer.invoke("launcher:open-logs"),
  installUpdate: () => ipcRenderer.invoke("launcher:update-install"),
  windowState: () => ipcRenderer.invoke("launcher:window-state"),
  windowControl: (action) => ipcRenderer.send("launcher:window-control", action),
  onWindowStateChanged: (listener) => subscription("launcher:window-state-changed", listener),
  onStateChanged: (listener) => subscription("launcher:state-changed", listener),
  onBrowserState: (listener) => subscription("launcher:browser-state", listener),
  onCouncilRuntime: (listener) => subscription("launcher:council-runtime", listener),
  onOperation: (listener) => subscription("launcher:operation", listener),
  onLog: (listener) => subscription("launcher:log", listener),
  onUpdateState: (listener) => subscription("launcher:update-state", listener),
});
